AWSTemplateFormatVersion: '2010-09-09'
Description: 'exit-marker-maker

  Exit marker maker lamdba

  '
Globals:
  Function:
    Timeout: 10
Outputs:
  ExitApi:
    Description: API Gateway endpoint URL for Prod stage for ExitLambda function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exit/
  ExitLambdaFunction:
    Description: ExitLambda Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ExitLambda
      - Arn
  ExitLambdaFunctionIamRole:
    Description: Implicit IAM Role created for ExitLambda function
    Value:
      Fn::GetAtt:
      - ExitLambdaRole
      - Arn
Resources:
  ExitLambda:
    Properties:
      CodeUri: s3://lambdas.leapdao.org/63301f65346816708281866792b99db7
      Environment:
        Variables:
          ETH_NETWORK: https://rinkeby.infura.io
          EXIT_HANDLER: '0x54177deD16B8fe8F9017D6c44704f6998A914e54'
          GAS_PRICE: 15
          PRIV_KEY: '0xB9D9D9C30B512B9BC6429A5864A0F3D0FA6174B8E2CD7189F878DC1221A38BBE'
          RATE: 0.95
      Events:
        Exit:
          Properties:
            Method: post
            Path: /exit
          Type: Api
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
